version: "3.3"

services:
  booking-api:
    container_name: jkbooks-api
    restart: always
    image: node:20.10.0
    ports:
      - 4001:9009
    volumes:
      - ./:/usr/src/jkbooks
    working_dir: /usr/src/jkbooks
    networks:
      - monorepo-network
    # FOR PRODUCTION
    command: bash -c "rm -rf dist npm install && npm run build && npm run start:prod"
    # FOR DEVELOPMENT
    # command: bash -c "npm install && npm run build && npm run start:dev"

  batch:
    container_name: batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - 4002:9010
    volumes:
      - ./:/usr/src/jkbooks
    working_dir: /usr/src/jkbooks
    networks:
      - monorepo-network
    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge
